/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bug.pbcore;

import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import static java.awt.Font.TRUETYPE_FONT;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author bkantor
 */
public class viewBox extends javax.swing.JFrame {

    /**
     * "Team1Score" "Team2Score" "Team1Name" "Team2Name" "Team1timeout"
     * "Team2timeout" "GameTime" "TimerTime" "Team1ScoreS" "Team2ScoreS" 
     * Creates
     * new form viewBox
     */
    viewBoxEvents viEvents = new viewBoxEvents(this);
    File f = new File("6809Chargen.ttf");
    Font Chargen;

    public viewBox() {
        initComponents();
        customize();
        viEvents.addVBoxEventsListener(new vBoxEventsListener() {
            @Override
            public void viewBoxEvent(viewBoxEvents e) {
                jTextField4.setText(e.data.get("Team1Name").toString());
                jTextField6.setText(e.data.get("Team2Name").toString());
                if ((Boolean) e.data.get("Team1timeout")) {
                    jTextField5.setText("X");
                } else {
                    jTextField5.setText("");
                }
                if ((Boolean) e.data.get("Team2timeout")) {
                    jTextField7.setText("X");

                } else {
                    jTextField7.setText("");
                }
                jTextField2.setText(String.format("%02d", e.data.get("Team1Score")));
                jTextField8.setText(String.format("%02d", e.data.get("Team2Score")));
                jTextField1.setText(e.data.get("GameTime").toString());
                jTextField9.setText(e.data.get("TimerTime").toString());
            }

            @Override
            public void viewBoxFieldEvent(String fieldName, viewBoxEvents e) {
                if("GameTime".equals(fieldName)){
                        jTextField1.setText(e.data.get(fieldName).toString());
                }
                if("GameTime".equals(fieldName)){
                        jTextField1.setText(e.data.get(fieldName).toString());
                }
                if("Team1Score".equals(fieldName)){
                        jTextField2.setText(String.format("%02d", e.data.get(fieldName)));
                }
                if("Team2Score".equals(fieldName)){
                        jTextField8.setText(String.format("%02d", e.data.get(fieldName)));
                }
                if("Team1Name".equals(fieldName)){
                        jTextField4.setText(e.data.get(fieldName).toString());
                }
                if("Team1Name".equals(fieldName)){
                        jTextField6.setText(e.data.get(fieldName).toString());
                }
                if("Team1timeout".equals(fieldName)){
                    if ((Boolean) e.data.get(fieldName)) {
                        jTextField5.setText("X");
                    } else {
                        jTextField5.setText("");
                    }
                }
                if("Team2timeout".equals(fieldName)){
                    if ((Boolean) e.data.get(fieldName)) {
                        jTextField7.setText("X");
                    } else {
                        jTextField7.setText("");
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ViewBOX");
        setAlwaysOnTop(true);
        setIconImages(null);
        setModalExclusionType(null);
        setPreferredSize(new java.awt.Dimension(800, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("00:00:00.00");
        jTextField1.setBorder(null);
        jTextField1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTextField1ComponentResized(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("ВРЕМЯ ИГРЫ");
        jTextField3.setBorder(null);

        jTextField9.setEditable(false);
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("00:00:00.00");
        jTextField9.setBorder(null);
        jTextField9.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTextField9ComponentResized(evt);
            }
        });

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("ТАЙМАУТ");
        jTextField10.setAutoscrolls(false);
        jTextField10.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jPanel1.setMinimumSize(new java.awt.Dimension(600, 100));

        jTextField6.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jTextField6.setText("jTextField4");
        jTextField6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTextField6ComponentResized(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jTextField4.setText("jTextField4");
        jTextField4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTextField4ComponentResized(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jTextField6)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField4)
                .addGap(1, 1, 1)
                .addComponent(jTextField6))
        );

        jPanel2.setMaximumSize(new java.awt.Dimension(500, 254));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 254));

        jPanel3.setMaximumSize(new java.awt.Dimension(400, 32767));
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 0, 0));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("X");
        jTextField7.setAutoscrolls(false);
        jTextField7.setMaximumSize(new java.awt.Dimension(65, 2147483647));
        jTextField7.setMinimumSize(new java.awt.Dimension(65, 19));
        jTextField7.setName(""); // NOI18N
        jTextField7.setPreferredSize(new java.awt.Dimension(65, 19));
        jTextField7.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTextField7ComponentResized(evt);
            }
        });
        jPanel3.add(jTextField7);

        jTextField8.setFont(new java.awt.Font("Dialog", 0, 96)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("00");
        jTextField8.setMaximumSize(new java.awt.Dimension(500, 214));
        jTextField8.setMinimumSize(new java.awt.Dimension(100, 122));
        jTextField8.setName(""); // NOI18N
        jTextField8.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTextField8ComponentResized(evt);
            }
        });
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField8);

        jPanel4.setMaximumSize(new java.awt.Dimension(400, 32767));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 0, 0));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("x");
        jTextField5.setAutoscrolls(false);
        jTextField5.setMaximumSize(new java.awt.Dimension(65, 2147483647));
        jTextField5.setMinimumSize(new java.awt.Dimension(65, 19));
        jTextField5.setName(""); // NOI18N
        jTextField5.setPreferredSize(new java.awt.Dimension(65, 19));
        jTextField5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTextField5ComponentResized(evt);
            }
        });
        jPanel4.add(jTextField5);

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 96)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("00");
        jTextField2.setMaximumSize(new java.awt.Dimension(500, 214));
        jTextField2.setMinimumSize(new java.awt.Dimension(100, 122));
        jTextField2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTextField2ComponentResized(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTextField9)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField9ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextField9ComponentResized
        //jTextField9.setText(String.valueOf(jTextField9.getHeight()));
        jTextField9.setFont(Chargen.deriveFont(Float.valueOf(String.valueOf(jTextField9.getHeight() * 0.7))));
    }//GEN-LAST:event_jTextField9ComponentResized

    private void jTextField1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextField1ComponentResized
        //jTextField1.setText(String.valueOf(jTextField1.getHeight()));
        jTextField1.setFont(Chargen.deriveFont(Float.valueOf(String.valueOf(jTextField1.getHeight() * 0.7))));
    }//GEN-LAST:event_jTextField1ComponentResized

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextField2ComponentResized
        jTextField2.setFont(Chargen.deriveFont(Float.valueOf(String.valueOf(jTextField2.getHeight() * 0.7))));
    }//GEN-LAST:event_jTextField2ComponentResized

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField8ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextField8ComponentResized
        jTextField8.setFont(Chargen.deriveFont(Float.valueOf(String.valueOf(jTextField8.getHeight() * 0.7))));
    }//GEN-LAST:event_jTextField8ComponentResized

    private void jTextField4ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextField4ComponentResized
        jTextField4.setFont(jTextField4.getFont().deriveFont(Float.valueOf(String.valueOf(jTextField4.getHeight() * 0.3))));
    }//GEN-LAST:event_jTextField4ComponentResized

    private void jTextField5ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextField5ComponentResized
        jTextField5.setFont(jTextField5.getFont().deriveFont(Float.valueOf(String.valueOf(jTextField5.getHeight() * 0.5))));
    }//GEN-LAST:event_jTextField5ComponentResized

    private void jTextField6ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextField6ComponentResized
        jTextField6.setFont(jTextField6.getFont().deriveFont(Float.valueOf(String.valueOf(jTextField6.getHeight() * 0.3))));
    }//GEN-LAST:event_jTextField6ComponentResized

    private void jTextField7ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTextField7ComponentResized
        jTextField7.setFont(jTextField7.getFont().deriveFont(Float.valueOf(String.valueOf(jTextField7.getHeight() * 0.5))));
    }//GEN-LAST:event_jTextField7ComponentResized

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    private void customize() {
        ImageIcon imgicon = new ImageIcon(getClass().getResource("/com/bug/resourse/ai.png"));
        setIconImage(imgicon.getImage());
        try {
            /* Set the Nimbus look and feel */
            Container c = getContentPane();
            Chargen = Font.createFont(TRUETYPE_FONT, f);
            c.setBackground(Color.BLACK);
            Chargen = Chargen.deriveFont(Font.PLAIN, 96);
            jTextField1.setForeground(Color.GREEN);
            jTextField1.setBackground(Color.BLACK);
            jTextField2.setForeground(Color.GREEN);
            jTextField2.setBackground(Color.BLACK);
            jTextField3.setForeground(Color.GREEN);
            jTextField3.setBackground(Color.BLACK);
            jTextField4.setForeground(Color.GREEN);
            jTextField4.setBackground(Color.BLACK);
            jTextField5.setForeground(Color.GREEN);
            jTextField5.setBackground(Color.BLACK);
            jTextField6.setForeground(Color.GREEN);
            jTextField6.setBackground(Color.BLACK);
            jTextField7.setForeground(Color.GREEN);
            jTextField7.setBackground(Color.BLACK);
            jTextField8.setForeground(Color.GREEN);
            jTextField8.setBackground(Color.BLACK);
            jTextField9.setForeground(Color.GREEN);
            jTextField9.setBackground(Color.BLACK);
            jTextField10.setForeground(Color.GREEN);
            jTextField10.setBackground(Color.BLACK);
            jTextField1.setFont(Chargen);
            jTextField2.setFont(Chargen.deriveFont(Float.valueOf(String.valueOf(jTextField2.getHeight() * 0.7))));
            jTextField8.setFont(Chargen.deriveFont(Float.valueOf(String.valueOf(jTextField8.getHeight() * 0.7))));
            jTextField9.setFont(Chargen);
            jPanel1.setBackground(Color.BLACK);
            jPanel2.setBackground(Color.BLACK);
            jPanel3.setBackground(Color.BLACK);
            jPanel4.setBackground(Color.BLACK);
        } catch (FontFormatException ex) {
            Logger.getLogger(viewBox.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(viewBox.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
